### ISSUE TITLE
Error in 'estimate' function

### ISSUE THREAD

**Issue by michellehunsche** [donaldRwilliams/BGGM#56]
I'm trying to estimate a network using the 'estimate' function, but when I try to plot the network I run into an error that says the data is 'NULL'. I looked through my code and it looks correct so I'm not sure why that might be happening, but I might be overlooking something. 

This is the code that I'm using to estimate the network:

### Estimate network

fit_socanxnet <- BGGM::bggm_missing(imp_socanxnet, method = "estimate", type =  "mixed", iter = 2000, seed=3)
sel_socanxnet <- BGGM::select(fit_socanxnet)
pred_socanxnet <- BGGM::predictability(fit_socanxnet)
sel_socanxnet$pcor_mat

### Print network

pdf("Network_Full Sample_Anxiety+Social Nodes.pdf")
qgraph::qgraph(sel_socanxnet$pcor_mat, layout="spring", mar=c(3,3,5,3),edge.color="blue", 
               esize=40, vsize=11, label.cex=0.95, colFactor=0.45, maximum=1)
dev.off()

But when I run the sel_socanxnet$pcor_mat line, I receive a NULL output. When I view the sel_socanxnet item, this is what I see: 

![screenshot](https://user-images.githubusercontent.com/71794682/95155029-0e118100-0748-11eb-806d-e2cdf6ea234e.png)

Any guidance would be much appreciated!

Thank you,
Michelle

**Comment by donaldRwilliams** [comment]
I am not sure why that does not work for you. I ran the examples in the documentation and each worked fine.

But I am not really sure what this is `sel_socanxnet$pcor_mat`. There is not an object called `pcor_mat` when using select. The object is called `pcor_adj` which I have when using `select`.

Now there should be a `pcor_mat` in the object `fit_socanxnet`.

If that does not work, then I will need the data so that I can exactly reproduce the error.

**Comment by ph-rast** [comment]
Not currently reproducible - feel free to submit new issue with reproducible data.
