### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by paulgovan** [donaldRwilliams/BGGM#6]
This issue is for [github.com/openjournals/joss-reviews/issues/2111](https://github.com/openjournals/joss-reviews/issues/2111).

There are no community guidelines for users or contributors who want to submit an issue or contribute to the package. This could be a simple statement referencing the built in issue and pull request features on github.

**Comment by donaldRwilliams** [comment]
We have addressed this in the readme:

https://github.com/donaldRwilliams/BGGM#bug-reports-and-feature-requests

**Comment by jayrobwilliams** [comment]
The README tells users where they can submit a bug report or feature request, but the review checklist includes information for people who wish to "Contribute to the software." Many projects include a `CONTRIBUTING` file in the repository. Here is the `ggplot2` one as an example: https://github.com/tidyverse/ggplot2/blob/master/CONTRIBUTING.md. While this is an especially involved document due to the size of the project, a `CONTRIBUTING` file should list etiquette for submitting pull requests and list any coding conventions the project uses.

**Comment by donaldRwilliams** [comment]
Noted. Will add this later today

**Comment by donaldRwilliams** [comment]
I decided against a contributing file, although I now include loose guidelines for those that want to contribute where I note the code convention (not sure I really have one, however, other than to only use base R)

**Comment by jayrobwilliams** [comment]
I'm satisfied with this implementation, but I'll let @paulgovan decide whether to close the issue as he opened it.

**Comment by donaldRwilliams** [comment]
Sounds good.

**Comment by donaldRwilliams** [comment]
I will close this, but can re open if needed

**Comment by donaldRwilliams** [comment]
To address this comment, we added a section (Bug Reports, Feature Requests, and Contributing) to the README and the paper
